#!/usr/bin/env python3
from datetime import datetime

print("Content-Type: text/html\r")
print("\r")
print("<h1>hello aboba</h1>")
print("<p>This message was generated by printhello.py CGI script!</p>")
print(f"<p><em>Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>")